# Generated by Django 6.0.1 on 2026-02-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', models.JSONField(default=tuple)),
            ],
        ),
        migrations.CreateModel(
            name='MatchManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success_rate', models.FloatField(default=0.0)),
                ('past_matches', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('is_private', models.BooleanField(default=False)),
                ('program_list', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('desired_program_types', models.JSONField(default=list)),
                ('matched_list', models.JSONField(default=list)),
                ('confirmed_matches', models.JSONField(default=list)),
                ('degree_level', models.IntegerField(choices=[(0, 'None'), (1, 'Practical Nursing'), (2, 'Asn'), (3, 'Bsn'), (4, 'Bsn Prelic'), (5, 'Grad Cert'), (6, 'Msn'), (7, 'Msn Prelic'), (8, 'Dnp'), (9, 'Phd')], default=0)),
            ],
        ),
    ]
