# Generated by Django 6.0.1 on 2026-02-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_role_customuser_account_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_attribute', models.JSONField()),
                ('scoring_weight', models.FloatField(default=0)),
                ('constraint_type', models.CharField(choices=[('HARD', 'Hard'), ('SOFT', 'Soft')], default='SOFT', max_length=10)),
            ],
        ),
    ]
