# Generated by Django 6.0.1 on 2026-02-24 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='school_name',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
