# Generated by Django 6.0.1 on 2026-02-17 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(0, 'None'), (1, 'Practical Nursing'), (2, 'Asn'), (3, 'Bsn'), (4, 'Bsn Prelic'), (5, 'Grad Cert'), (6, 'Msn'), (7, 'Msn Prelic'), (8, 'Dnp'), (9, 'Phd')], default=0)),
                ('specialty', models.IntegerField(choices=[(0, 'None'), (1, 'Adult Geron Acute'), (2, 'Adult Geron Prim'), (3, 'Adult Geron Clin Spec'), (4, 'Family Np'), (5, 'Health It'), (6, 'Midwifery'), (7, 'Nursing Admin Lead'), (8, 'Nurse Edu'), (9, 'Ped Clin Spec'), (10, 'Ped Acu Np'), (11, 'Psych Np'), (12, 'Womens Health Np'), (13, 'Transcultural'), (14, 'Innovations'), (15, 'Integ Healing'), (16, 'Neonat Np'), (17, 'Nurse Anesth'), (18, 'Public Health'), (19, 'Nursing Promotion'), (20, 'Chronic Cond Prev'), (21, 'Pop Health'), (22, 'Sympt Management')], default=0)),
                ('format', models.IntegerField(choices=[(0, 'None'), (1, 'Traditional'), (2, 'Accelerated'), (3, 'Bridge'), (4, 'Post Bacc'), (5, 'N A')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.IntegerField(choices=[(0, 'None'), (1, 'Part Time'), (2, 'Full Time')], default=0)),
                ('tuition', models.FloatField(default=0.0)),
                ('dorm_requirement', models.IntegerField(choices=[(0, 'None'), (1, 'Required'), (2, 'Optional')], default=0)),
                ('dorm_availability', models.IntegerField(choices=[(0, 'None'), (1, 'Available'), (2, 'Limited'), (3, 'Unavailable')], default=0)),
                ('acceptance_rate', models.BooleanField(default=False)),
                ('esl_support', models.BooleanField(default=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.school')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('approval_status', models.BooleanField(default=False)),
                ('matched_students', models.JSONField(default=list)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.school')),
                ('program_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.programprofile')),
            ],
        ),
    ]
